"""
Pipeline for ODA Consortium Intelligence.

This version uses the Partner Master DB generated by partner_master_builder.py.
It keeps the old rule-based matching as a fallback, but the main matching path is:

    component keywords -> required capability tags -> Partner Master DB -> scored partners

Expected files:
- data/koica_iati.csv
- data/koica_humanitarian.csv
- data/nonprofit_national.csv
- partner_db/partners.csv
- partner_db/partner_master_summary.csv
- partner_db/partner_capabilities.csv
- partner_db/partner_projects.csv
- partner_db/project_participants.csv
"""

from __future__ import annotations

import json
import os
import re
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import pandas as pd


# -----------------------------------------------------------------------------
# Static taxonomy / weights
# -----------------------------------------------------------------------------

RELEVANT_MINISTRIES = {
    "외교부", "기후에너지환경부", "환경부", "산림청", "해양수산부", "농림축산식품부",
    "중소벤처기업부", "국무조정실", "교육부",
}

MULTILATERAL_PAT = re.compile(
    r"(WHO|UNDP|UNICEF|UN-?Habitat|UNEP|UNESCO|WFP|FAO|IOM|ADB|GGGI|IFAD|UNFPA|UN\b)",
    re.IGNORECASE,
)

# This taxonomy should stay aligned with partner_master_builder.py.
CAPABILITY_KEYWORDS: Dict[str, List[str]] = {
    "ODA_PMC": [
        "pmc", "project management", "사업관리", "사업 수행관리", "수행관리",
        "성과관리", "pdm", "m&e", "monitoring", "evaluation", "평가",
        "모니터링", "사업성과", "산출물 관리", "project coordination",
    ],
    "project_design_policy_research": [
        "정책연구", "정책 연구", "전략", "타당성", "예비조사", "기초선",
        "baseline", "조사", "컨설팅", "consulting", "feasibility", "strategy",
        "master plan", "마스터플랜", "계획 수립", "관리계획", "manual", "매뉴얼",
    ],
    "forestry_restoration": [
        "산림", "임업", "조림", "복원", "생태", "맹그로브", "mangrove",
        "forest", "forestry", "restoration", "reforestation", "biodiversity",
        "생물다양성", "보호지역", "ecosystem", "wetland", "습지",
    ],
    "GIS_remote_sensing": [
        "gis", "드론", "drone", "원격탐사", "remote sensing", "mapping", "매핑",
        "공간정보", "geospatial", "gps", "위성", "satellite", "ict", "정보화",
        "데이터", "data", "forest geographic", "fgis",
    ],
    "aquaculture_livelihood": [
        "양식", "수산", "어업", "fisheries", "aquaculture", "shrimp", "새우",
        "livelihood", "생계", "소득", "income", "community", "커뮤니티", "주민",
        "지역개발", "value chain", "가치사슬", "농업", "agriculture",
    ],
    "capacity_building_training": [
        "역량강화", "capacity", "capacity building", "교육", "training", "연수",
        "훈련", "워크숍", "workshop", "초청연수", "교육프로그램", "홍보자료",
        "awareness", "인식제고", "세미나", "seminar",
    ],
    "construction_infrastructure": [
        "건축", "건설", "시공", "리모델링", "remodeling", "renovation",
        "infrastructure", "인프라", "building", "construction", "센터", "설계",
        "토목", "시설", "facility",
    ],
    "procurement_equipment": [
        "기자재", "장비", "조달", "equipment", "procurement", "실험실", "laboratory",
        "vehicle", "차량", "it 장비", "device", "기기", "material", "supplies",
    ],
    "health_wash_humanitarian": [
        "wash", "보건", "위생", "health", "sanitation", "water", "식수", "난민",
        "refugee", "인도적", "humanitarian", "긴급구호", "재난", "disaster",
    ],
    "education_youth": [
        "교육", "학교", "학생", "아동", "청소년", "youth", "school", "student",
        "child", "children", "curriculum", "교재", "literacy", "문해",
    ],
}

ROLE_BY_CAPABILITY = {
    "ODA_PMC": "PMC / M&E",
    "project_design_policy_research": "Planning / policy research",
    "forestry_restoration": "Forestry restoration",
    "GIS_remote_sensing": "ICT / GIS / remote sensing",
    "aquaculture_livelihood": "Aquaculture / livelihood",
    "capacity_building_training": "Capacity building / training",
    "construction_infrastructure": "Construction / infrastructure",
    "procurement_equipment": "Equipment procurement",
    "health_wash_humanitarian": "Humanitarian / WASH",
    "education_youth": "Education / awareness",
}

# Sector text can be too short, so add deterministic hints.
SECTOR_TO_CAPABILITY_HINTS = {
    "산림/ICT": ["forestry_restoration", "GIS_remote_sensing", "project_design_policy_research"],
    "산림/환경": ["forestry_restoration"],
    "수산/농업": ["aquaculture_livelihood"],
    "건축/인프라": ["construction_infrastructure"],
    "조달": ["procurement_equipment"],
    "교육/역량강화": ["capacity_building_training"],
}


# -----------------------------------------------------------------------------
# General helpers
# -----------------------------------------------------------------------------

def safe_str(value: Any) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass
    return str(value).strip()


def read_csv_safely(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    encodings = ["utf-8-sig", "utf-8", "cp949", "euc-kr"]
    last_error: Optional[Exception] = None
    for enc in encodings:
        try:
            return pd.read_csv(path, dtype=str, encoding=enc).fillna("")
        except Exception as exc:
            last_error = exc
    raise RuntimeError(f"Could not read CSV: {path}. Last error: {last_error}")


def find_existing_file(data_dir: Path, filename: str) -> Path:
    """Find CSV in data_dir first, then one level up. Useful for local demos."""
    direct = data_dir / filename
    if direct.exists():
        return direct
    parent = data_dir.parent / filename
    if parent.exists():
        return parent
    return direct


def _kw_hits(text: str, keywords: Sequence[str]) -> List[str]:
    t = safe_str(text).lower()
    hits = []
    for k in keywords:
        kk = safe_str(k).lower()
        if kk and kk in t:
            hits.append(k)
    return hits


def _to_int(value: Any, default: int = 0) -> int:
    text = re.sub(r"[^0-9\-]", "", safe_str(value))
    if not text:
        return default
    try:
        return int(text)
    except Exception:
        return default


def _to_float(value: Any, default: float = 0.0) -> float:
    text = re.sub(r"[^0-9\.\-]", "", safe_str(value))
    if not text:
        return default
    try:
        return float(text)
    except Exception:
        return default


# -----------------------------------------------------------------------------
# Loading data
# -----------------------------------------------------------------------------

def load_partner_db(partner_db_dir: str | Path) -> Dict[str, pd.DataFrame]:
    """Load Partner Master DB generated by partner_master_builder.py."""
    p = Path(partner_db_dir)
    tables = {
        "partners": read_csv_safely(p / "partners.csv"),
        "summary": read_csv_safely(p / "partner_master_summary.csv"),
        "capabilities": read_csv_safely(p / "partner_capabilities.csv"),
        "projects": read_csv_safely(p / "partner_projects.csv"),
        "participants": read_csv_safely(p / "project_participants.csv"),
        "sources": read_csv_safely(p / "partner_sources.csv"),
        "aliases": read_csv_safely(p / "partner_aliases.csv"),
        "edges": read_csv_safely(p / "partner_edges.csv"),
        "procurement_records": read_csv_safely(p / "procurement_records.csv"),
    }
    return tables


def partner_db_available(partner_db: Dict[str, pd.DataFrame]) -> bool:
    return (
        isinstance(partner_db, dict)
        and not partner_db.get("summary", pd.DataFrame()).empty
        and not partner_db.get("capabilities", pd.DataFrame()).empty
    )


def load_data(data_dir: str | Path, partner_db_dir: str | Path | None = None) -> Dict[str, Any]:
    """Load raw source CSVs plus Partner Master DB if available."""
    data_dir = Path(data_dir)
    if partner_db_dir is None:
        # Normal project layout: project/data + project/partner_db.
        # Flat demo layout: /mnt/data + /mnt/data/partner_db.
        if (data_dir / "partner_db").exists():
            partner_db_dir = data_dir / "partner_db"
        else:
            partner_db_dir = data_dir.parent / "partner_db"
    else:
        partner_db_dir = Path(partner_db_dir)

    d: Dict[str, Any] = {}
    d["iati"] = read_csv_safely(find_existing_file(data_dir, "koica_iati.csv"))
    d["humanitarian"] = read_csv_safely(find_existing_file(data_dir, "koica_humanitarian.csv"))
    d["nonprofit"] = read_csv_safely(find_existing_file(data_dir, "nonprofit_national.csv"))
    d["partner_db"] = load_partner_db(partner_db_dir)
    return d


# -----------------------------------------------------------------------------
# Component -> required capability inference
# -----------------------------------------------------------------------------

def component_text(component: Dict[str, Any]) -> str:
    pieces: List[str] = []
    for key in ["id", "name", "desc", "description", "sector"]:
        pieces.append(safe_str(component.get(key, "")))
    for k in component.get("keywords", []) or []:
        pieces.append(safe_str(k))
    return " ".join(pieces).lower()


def infer_required_capabilities(component: Dict[str, Any], top_n: int = 4) -> List[Dict[str, Any]]:
    """Infer capability tags required by a component."""
    text = component_text(component)
    raw_scores: Dict[str, Dict[str, Any]] = {}

    for cap, keywords in CAPABILITY_KEYWORDS.items():
        hits = _kw_hits(text, keywords)
        if hits:
            raw_scores[cap] = {
                "capability_tag": cap,
                "weight": min(1.0, 0.45 + 0.15 * len(set(hits))),
                "hits": sorted(set(hits), key=lambda x: str(x)),
            }

    sector = safe_str(component.get("sector", ""))
    for cap in SECTOR_TO_CAPABILITY_HINTS.get(sector, []):
        if cap not in raw_scores:
            raw_scores[cap] = {"capability_tag": cap, "weight": 0.65, "hits": [sector]}
        else:
            raw_scores[cap]["weight"] = min(1.0, raw_scores[cap]["weight"] + 0.2)
            raw_scores[cap]["hits"] = sorted(set(raw_scores[cap]["hits"] + [sector]))

    # Sector guardrail: prevent terms such as "education center" from turning a
    # construction component into an education component.
    sector_allowed = {
        "산림/ICT": {"forestry_restoration", "GIS_remote_sensing", "project_design_policy_research", "ODA_PMC"},
        "산림/환경": {"forestry_restoration", "project_design_policy_research", "GIS_remote_sensing", "ODA_PMC"},
        "수산/농업": {"aquaculture_livelihood", "project_design_policy_research", "capacity_building_training", "ODA_PMC"},
        "건축/인프라": {"construction_infrastructure", "procurement_equipment", "ODA_PMC"},
        "조달": {"procurement_equipment", "construction_infrastructure", "ODA_PMC"},
        "교육/역량강화": {"capacity_building_training", "education_youth", "ODA_PMC", "project_design_policy_research"},
    }.get(sector)
    if sector_allowed:
        raw_scores = {k: v for k, v in raw_scores.items() if k in sector_allowed}

    if not raw_scores:
        # Generic fallback for ODA projects.
        raw_scores["ODA_PMC"] = {"capability_tag": "ODA_PMC", "weight": 0.45, "hits": ["fallback"]}
        raw_scores["project_design_policy_research"] = {
            "capability_tag": "project_design_policy_research",
            "weight": 0.45,
            "hits": ["fallback"],
        }

    ordered = sorted(raw_scores.values(), key=lambda x: x["weight"], reverse=True)
    return ordered[:top_n]


def suggested_role(required_caps: List[Dict[str, Any]]) -> str:
    if not required_caps:
        return "Implementation partner"
    labels = [ROLE_BY_CAPABILITY.get(c["capability_tag"], c["capability_tag"]) for c in required_caps[:2]]
    return " + ".join(labels)


STRONG_TECH_TERMS = {
    "GIS_remote_sensing": [
        "gis", "드론", "drone", "원격탐사", "remote sensing", "mapping", "매핑",
        "공간정보", "geospatial", "gps", "위성", "satellite", "fgis",
    ],
    "construction_infrastructure": [
        "건축", "건설", "시공", "리모델링", "remodeling", "renovation",
        "infrastructure", "building", "construction", "토목", "설계",
    ],
    "procurement_equipment": [
        "기자재", "장비", "조달", "equipment", "procurement", "실험실",
        "laboratory", "vehicle", "차량", "device",
    ],
}

GENERIC_COMPONENT_TERMS = {
    "ict", "data", "데이터", "조사", "survey", "교육", "센터", "center",
    "사업", "관리", "지원", "환경", "생태", "capacity", "training",
}


def _evidence_blob(row: pd.Series) -> str:
    return (
        safe_str(row.get("evidence_keywords", "")) + " "
        + safe_str(row.get("evidence_summary", ""))
    ).lower()


def _precision_multiplier(row: pd.Series, component: Dict[str, Any]) -> float:
    """Reduce false positives from broad keywords such as ICT/data/center."""
    cap = safe_str(row.get("capability_tag"))
    text = component_text(component)
    blob = _evidence_blob(row)

    strong_terms = STRONG_TECH_TERMS.get(cap, [])
    if strong_terms and any(t.lower() in text for t in strong_terms):
        strong_hits = [t for t in strong_terms if t.lower() in blob]
        if not strong_hits:
            return 0.30
        if len(strong_hits) >= 2:
            return 1.20
        return 1.00

    return 1.00


def _component_keyword_overlap(row: pd.Series, component: Dict[str, Any]) -> float:
    """Small bonus for direct component-keyword evidence, excluding generic words."""
    blob = _evidence_blob(row)
    kws = [safe_str(k).lower() for k in component.get("keywords", []) or []]
    kws += [safe_str(component.get("name", "")).lower(), safe_str(component.get("sector", "")).lower()]

    hits = []
    for kw in kws:
        if not kw or kw in GENERIC_COMPONENT_TERMS or len(kw) < 2:
            continue
        if kw in blob:
            hits.append(kw)
    return min(10.0, len(set(hits)) * 2.5)


# -----------------------------------------------------------------------------
# Partner Master DB matching
# -----------------------------------------------------------------------------

def match_domestic_from_partner_db(
    component: Dict[str, Any],
    partner_db: Dict[str, pd.DataFrame],
    recipient_country: str = "스리랑카",
    top_n: int = 6,
    domestic_only: bool = True,
) -> pd.DataFrame:
    """Rank partners against a component using Partner Master DB evidence."""
    summary = partner_db.get("summary", pd.DataFrame()).copy()
    caps = partner_db.get("capabilities", pd.DataFrame()).copy()
    projects = partner_db.get("projects", pd.DataFrame()).copy()

    if summary.empty or caps.empty:
        return pd.DataFrame(columns=["기관", "점수", "출처", "근거"])

    required = infer_required_capabilities(component)
    required_tags = [r["capability_tag"] for r in required]
    required_weights = {r["capability_tag"]: float(r["weight"]) for r in required}
    required_hit_map = {r["capability_tag"]: r.get("hits", []) for r in required}

    caps = caps[caps["capability_tag"].isin(required_tags)].copy()
    if caps.empty:
        return pd.DataFrame(columns=["기관", "점수", "출처", "근거"])

    # Normalize numeric fields.
    caps["score_num"] = caps["score"].apply(_to_float)
    caps["evidence_count_num"] = caps["evidence_count"].apply(_to_int)
    caps["last_evidence_year_num"] = caps["last_evidence_year"].apply(_to_int)
    caps["required_weight"] = caps["capability_tag"].map(required_weights).fillna(0.5)
    caps["precision_multiplier"] = caps.apply(lambda r: _precision_multiplier(r, component), axis=1)
    caps["keyword_overlap_bonus"] = caps.apply(lambda r: _component_keyword_overlap(r, component), axis=1)
    caps["capability_component_score"] = (
        caps["score_num"] * caps["required_weight"] * caps["precision_multiplier"]
        + caps["keyword_overlap_bonus"]
    )

    # Aggregate capability evidence per partner.
    agg = caps.groupby("partner_id", as_index=False).agg(
        capability_fit=("capability_component_score", "sum"),
        evidence_count=("evidence_count_num", "sum"),
        last_evidence_year=("last_evidence_year_num", "max"),
        matched_capabilities=("capability_tag", lambda s: ", ".join(dict.fromkeys(s.astype(str).tolist()))),
        evidence_keywords=("evidence_keywords", lambda s: ", ".join(sorted(set(", ".join(s.astype(str)).split(", "))))[:280]),
        evidence_summary=("evidence_summary", lambda s: " | ".join(s.astype(str).head(2).tolist())[:500]),
    )

    merged = agg.merge(summary, on="partner_id", how="left")

    # Filter out multilaterals for domestic matching, while keeping universities/NGOs/firms/etc.
    if domestic_only and "org_type" in merged.columns:
        intl_types = {"multilateral", "international_organization", "multilateral_development_bank"}
        merged = merged[~merged["org_type"].astype(str).isin(intl_types)].copy()

    # Country/regional bonus from project table.
    country_bonus_map: Dict[str, float] = {}
    country_evidence_map: Dict[str, str] = {}
    if not projects.empty and recipient_country:
        # Attach participants if available for project-to-partner relation.
        participants = partner_db.get("participants", pd.DataFrame()).copy()
        if not participants.empty:
            pp = participants.merge(projects[["project_id", "country", "project_title_ko"]], on="project_id", how="left")
            pp["country"] = pp["country"].fillna("")
            for pid, g in pp.groupby("partner_id"):
                exact = g[g["country"].astype(str).str.contains(recipient_country, na=False)]
                if len(exact):
                    country_bonus_map[pid] = 7.0
                    country_evidence_map[pid] = f"{recipient_country} project experience"

    merged["country_bonus"] = merged["partner_id"].map(country_bonus_map).fillna(0.0)
    merged["country_evidence"] = merged["partner_id"].map(country_evidence_map).fillna("")

    # Source/project credibility.
    merged["source_count_num"] = merged.get("source_count", 0)
    merged["project_count_num"] = merged.get("project_count", 0)
    merged["source_count_num"] = merged["source_count_num"].apply(_to_int)
    merged["project_count_num"] = merged["project_count_num"].apply(_to_int)

    # Recency bonus. Unknown year = 0.
    merged["recency_bonus"] = merged["last_evidence_year"].apply(lambda y: max(0, min(8, (_to_int(y) - 2018) * 1.0)))
    merged["evidence_bonus"] = merged["evidence_count"].apply(lambda x: min(12, _to_int(x) * 1.2))
    merged["source_bonus"] = merged["source_count_num"].apply(lambda x: min(5, x * 1.5))
    merged["project_bonus"] = merged["project_count_num"].apply(lambda x: min(8, x * 0.5))

    # Penalize generic over-broad institutions slightly when evidence is only from IATI title parsing.
    merged["intl_penalty"] = 0.0
    if "first_seen_source" in merged.columns:
        merged.loc[merged["first_seen_source"].astype(str).eq("koica_iati"), "intl_penalty"] = 2.0

    merged["raw_score"] = (
        merged["capability_fit"] * 0.55
        + merged["evidence_bonus"]
        + merged["recency_bonus"]
        + merged["source_bonus"]
        + merged["project_bonus"]
        + merged["country_bonus"]
        - merged["intl_penalty"]
    )
    merged["점수"] = merged["raw_score"].clip(lower=0, upper=100).round(1)

    # Build UI-compatible fields.
    rows: List[Dict[str, Any]] = []
    for _, r in merged.sort_values("점수", ascending=False).head(top_n).iterrows():
        caps_str = safe_str(r.get("matched_capabilities", ""))
        cap_list = [c.strip() for c in caps_str.split(",") if c.strip()]
        role = " + ".join([ROLE_BY_CAPABILITY.get(c, c) for c in cap_list[:2]]) or suggested_role(required)

        required_hits = []
        for cap in cap_list:
            required_hits.extend(required_hit_map.get(cap, []))
        required_hits = sorted(set(required_hits))[:8]

        source_bits = []
        if _to_int(r.get("project_count", 0)):
            source_bits.append(f"project evidence {_to_int(r.get('project_count', 0))}건")
        if _to_int(r.get("source_count", 0)):
            source_bits.append(f"source {_to_int(r.get('source_count', 0))}개")
        if safe_str(r.get("country_evidence", "")):
            source_bits.append(safe_str(r.get("country_evidence", "")))

        evidence_keywords = safe_str(r.get("evidence_keywords", ""))
        evidence_keywords = re.sub(r"\s+", " ", evidence_keywords).strip(" ,")
        evidence_summary = safe_str(r.get("evidence_summary", ""))
        evidence_summary = re.sub(r"\s+", " ", evidence_summary)

        reason_parts = [
            f"role={role}",
            f"capability={caps_str}",
        ]
        if required_hits:
            reason_parts.append(f"component keywords={required_hits}")
        if evidence_keywords:
            reason_parts.append(f"evidence keywords={evidence_keywords[:160]}")
        if evidence_summary:
            reason_parts.append(f"evidence={evidence_summary[:220]}")

        rows.append({
            "partner_id": safe_str(r.get("partner_id")),
            "기관": safe_str(r.get("canonical_name_ko")) or safe_str(r.get("canonical_name_en")) or safe_str(r.get("partner_id")),
            "점수": float(r.get("점수", 0)),
            "출처": "Partner Master DB" + (" · " + " · ".join(source_bits) if source_bits else ""),
            "근거": " · ".join(reason_parts),
            "추천역할": role,
            "역량태그": caps_str,
            "evidence_count": int(_to_int(r.get("evidence_count", 0))),
            "last_evidence_year": int(_to_int(r.get("last_evidence_year", 0))),
            "org_type": safe_str(r.get("org_type", "")),
            "legal_type": safe_str(r.get("legal_type", "")),
        })

    return pd.DataFrame(rows)


# -----------------------------------------------------------------------------
# Legacy domestic matching fallback
# -----------------------------------------------------------------------------

def match_domestic_legacy(
    component: Dict[str, Any],
    humanitarian: pd.DataFrame,
    nonprofit: pd.DataFrame,
    recipient_country: str = "스리랑카",
    top_n: int = 6,
) -> pd.DataFrame:
    """Legacy rule-based matching. Kept as fallback when partner_db is absent."""
    kws = component.get("keywords", []) or []
    rows: List[Dict[str, Any]] = []

    if humanitarian is not None and not humanitarian.empty:
        hum = humanitarian.copy()
        hum["_txt"] = (
            hum.get("사업명_국문", "").astype(str) + " "
            + hum.get("사업명_영문", "").astype(str) + " "
            + hum.get("지역", "").astype(str) + " "
            + hum.get("담당부서", "").astype(str)
        )
        if "수행기관" in hum.columns:
            for org, g in hum.groupby("수행기관"):
                if not safe_str(org):
                    continue
                hits: set[str] = set()
                countries: set[str] = set()
                for _, rr in g.iterrows():
                    hits.update(_kw_hits(rr.get("_txt", ""), kws))
                    countries.add(safe_str(rr.get("국가명", "")))
                if not hits:
                    continue
                score = len(hits) * 3
                note = f"KOICA 수행실적 {len(g)}건"
                if recipient_country in countries:
                    score += 5
                    note += f" · {recipient_country} 경험"
                for sub in re.split(r"[,\u3001·/]", safe_str(org)):
                    sub = sub.strip()
                    if sub:
                        rows.append({
                            "기관": sub,
                            "점수": score,
                            "출처": "실적기반",
                            "근거": f"{note} · 키워드 {sorted(hits)}",
                        })

    if nonprofit is not None and not nonprofit.empty:
        npf = nonprofit.copy()
        npf["_txt"] = npf.get("단체명", "").astype(str) + " " + npf.get("주된사업", "").astype(str)
        for _, rr in npf.iterrows():
            hits = _kw_hits(rr.get("_txt", ""), kws)
            if not hits:
                continue
            score = len(hits) * 2
            note = ""
            if safe_str(rr.get("등록기관", "")) in RELEVANT_MINISTRIES:
                score += 4
                note = f"{rr.get('등록기관', '')} 등록"
            rows.append({
                "기관": rr.get("단체명", ""),
                "점수": score,
                "출처": "등록기반",
                "근거": f"{note} · 키워드 {hits}".strip(" ·"),
            })

    if not rows:
        return pd.DataFrame(columns=["기관", "점수", "출처", "근거"])
    df = pd.DataFrame(rows)
    df = df.sort_values("점수", ascending=False).drop_duplicates("기관").head(top_n)
    return df.reset_index(drop=True)


def match_domestic(
    component: Dict[str, Any],
    humanitarian: pd.DataFrame | None = None,
    nonprofit: pd.DataFrame | None = None,
    recipient_country: str = "스리랑카",
    top_n: int = 6,
    partner_db: Optional[Dict[str, pd.DataFrame]] = None,
) -> pd.DataFrame:
    """
    Public matching function used by app.py.

    Preferred path: Partner Master DB.
    Fallback path: legacy keyword matching against KOICA humanitarian + NPO registry.
    """
    if partner_db_available(partner_db or {}):
        out = match_domestic_from_partner_db(component, partner_db or {}, recipient_country, top_n=top_n)
        if not out.empty:
            return out
    return match_domestic_legacy(component, humanitarian if humanitarian is not None else pd.DataFrame(), nonprofit if nonprofit is not None else pd.DataFrame(), recipient_country, top_n)


# -----------------------------------------------------------------------------
# Host-country footprint / graph evidence
# -----------------------------------------------------------------------------

def iati_country_footprint(iati: pd.DataFrame, country: str = "스리랑카") -> Tuple[pd.DataFrame, pd.Series, Dict[str, int]]:
    if iati is None or iati.empty:
        return pd.DataFrame(), pd.Series(dtype=int), {}
    if "수원국" not in iati.columns:
        return pd.DataFrame(), pd.Series(dtype=int), {}

    sl = iati[iati["수원국"].astype(str).str.contains(country, na=False)].copy()
    sectors = sl["사업분야명"].value_counts() if "사업분야명" in sl.columns else pd.Series(dtype=int)

    partners: Dict[str, int] = {}
    title_cols = [c for c in ["사업명(한글)", "사업명(영문)"] if c in sl.columns]
    for col in title_cols:
        for name in sl[col].astype(str).tolist():
            for m in MULTILATERAL_PAT.findall(name):
                key = m.upper().replace("-", "")
                partners[key] = partners.get(key, 0) + 1
    return sl, sectors, partners


def co_implementation_edges(humanitarian: pd.DataFrame | None = None, partner_db: Optional[Dict[str, pd.DataFrame]] = None) -> List[Tuple[str, str, str]]:
    """Extract verified / demo co-delivery edges.

    Priority:
    1) partner_db/partner_edges.csv generated by procurement ingest or mock seed.
    2) legacy humanitarian CSV where 수행기관 contains multiple organizations.

    Returned values are display names, because graph_view connects edges by visible node labels.
    """
    edges: List[Tuple[str, str, str]] = []

    # New path: Partner Master DB edges. partner_a / partner_b may be either
    # partner_id or display name. Resolve IDs to canonical Korean names when possible.
    if partner_db:
        edge_df = partner_db.get("edges", pd.DataFrame()).copy()
        summary = partner_db.get("summary", pd.DataFrame()).copy()
        name_map: Dict[str, str] = {}
        if not summary.empty and {"partner_id", "canonical_name_ko"}.issubset(summary.columns):
            for _, sr in summary.iterrows():
                pid = safe_str(sr.get("partner_id"))
                name = safe_str(sr.get("canonical_name_ko")) or safe_str(sr.get("canonical_name_en")) or pid
                if pid:
                    name_map[pid] = name

        if not edge_df.empty and {"partner_a", "partner_b"}.issubset(edge_df.columns):
            for _, r in edge_df.iterrows():
                a_raw = safe_str(r.get("partner_a"))
                b_raw = safe_str(r.get("partner_b"))
                if not a_raw or not b_raw:
                    continue
                a = name_map.get(a_raw, a_raw)
                b = name_map.get(b_raw, b_raw)
                title = safe_str(r.get("evidence_text")) or safe_str(r.get("project_id")) or "Co-delivery evidence"
                edges.append((a, b, title))

    # Legacy path: humanitarian CSV consortium notation.
    if humanitarian is not None and not humanitarian.empty and "수행기관" in humanitarian.columns:
        for _, r in humanitarian.iterrows():
            org = safe_str(r.get("수행기관", ""))
            parts = [p.strip() for p in re.split(r"[,\u3001·]", org) if p.strip()]
            if len(parts) > 1:
                title = safe_str(r.get("사업명_국문", "")) or safe_str(r.get("사업명_영문", ""))
                for i in range(len(parts)):
                    for j in range(i + 1, len(parts)):
                        edges.append((parts[i], parts[j], title))

    # Deduplicate while preserving order.
    seen = set()
    out: List[Tuple[str, str, str]] = []
    for a, b, title in edges:
        key = tuple(sorted([a, b]) + [title])
        if key not in seen:
            seen.add(key)
            out.append((a, b, title))
    return out


# -----------------------------------------------------------------------------
# Consortium recommendation
# -----------------------------------------------------------------------------

def recommend_consortium(
    components: List[Dict[str, Any]],
    humanitarian: pd.DataFrame | None,
    nonprofit: pd.DataFrame | None,
    field_partners: List[Dict[str, Any]],
    recipient_country: str = "스리랑카",
    partner_db: Optional[Dict[str, pd.DataFrame]] = None,
) -> Tuple[List[Dict[str, Any]], float, Dict[str, float]]:
    """Recommend one domestic lead/candidate per component and calculate demo score."""
    rec: List[Dict[str, Any]] = []

    for c in components:
        m = match_domestic(c, humanitarian, nonprofit, recipient_country, top_n=5, partner_db=partner_db)
        lead = m.iloc[0].to_dict() if len(m) else None
        fps = [f["name"] for f in field_partners if c.get("id") in f.get("components", [])]
        item = {
            "component": c,
            "국내후보": lead,
            "domestic": lead,
            "국내후보목록": m.to_dict("records"),
            "domestic_candidates": m.to_dict("records"),
            "현지파트너": fps,
            "field": fps,
            "required_capabilities": infer_required_capabilities(c),
        }
        rec.append(item)

    covered = sum(1 for r in rec if r["국내후보"])
    coverage = covered / max(len(components), 1)
    avg_match = (
        sum(float(r["국내후보"].get("점수", 0)) for r in rec if r["국내후보"])
        / max(covered, 1)
    )
    field_link = sum(1 for r in rec if r["현지파트너"]) / max(len(components), 1)

    # More intuitive than old formula: 40 coverage + 30 normalized domestic fit + 30 field linkage.
    domestic_fit_component = min(avg_match, 100) / 100 * 30
    total = round(coverage * 40 + domestic_fit_component + field_link * 30, 1)
    breakdown = {
        "분야 커버리지(40)": round(coverage * 40, 1),
        "국내 매칭 강도(30)": round(domestic_fit_component, 1),
        "현지 연계(30)": round(field_link * 30, 1),
    }
    return rec, total, breakdown


# -----------------------------------------------------------------------------
# data.go.kr / KOICA / Nara API stubs
# -----------------------------------------------------------------------------

NARA_CNTRCT_PROCESS = "http://apis.data.go.kr/1230000/ao/CntrctProcssIntgOpenService"
KOICA_ODA_PROCUREMENT_BASE = "http://apis.data.go.kr/B260004"  # confirm exact operations in data.go.kr


def fetch_nara_bid_process(bid_no: str, service_key: str, num_rows: int = 10) -> Optional[Dict[str, Any]]:
    """Nara contract-process integrated API: notice -> award -> contract by bid notice no."""
    if not service_key:
        return None
    op = "getCntrctProcssIntgOpenUsrvc"  # confirm in Swagger for exact service subtype.
    params = {
        "serviceKey": service_key,
        "bidNtceNo": bid_no,
        "numOfRows": num_rows,
        "pageNo": 1,
        "type": "json",
    }
    url = f"{NARA_CNTRCT_PROCESS}/{op}?" + urllib.parse.urlencode(params, safe="%")
    try:
        with urllib.request.urlopen(url, timeout=10) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        return {"error": str(e)}
